version: "1.0"

services:
    app:
        container_name: app
        image: laravel:1.0.0
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        restart: always

    db:
        container_name: db
        image: postgres:16
        ports:
            - "4321:4321"
        environment:
            POSTGRES_DB: nukerduit
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
